# yazi.toml
[mgr]
show_hidden = true

[opener]

image = [
{ run = 'feh "$@"' },
]
text = [
	{ run = 'nvim "$@"', block = true, desc = "nvim", for = "linux" },
]

music = [
{ run = 'ffplay -nodisp -autoexit "$@"' },
]

[open]

rules = [

{ name = "*.jpg", use = "image" },

{ name = "*.png", use = "image" },

{ name = "*.conf", use = "text" },

{ name = "*.toml", use = "text" },

{ name = "*.txt", use = "text" },

{ name = "*.ini", use = "text" },

{ name = "*.jsonc", use = "text" },

{ name = "*.yml", use = "text" },

{ name = "*.json", use = "text" },

{ name = "*.lua", use = "text" },

{ name = "*.md", use = "text" },

{ name = "*.css", use = "text" },

{ name = "*.mp3", use = "music"},

{ name = "*.wav", use = "music"},

{ name = "*.ogg", use = "music"}

]
