# yazi.toml
[mgr]
show_hidden = true

[opener]

imageedit = [
{ run = 'pinta "$@"', desc = "Pinta Image Editor" }
]

image = [
{ run = 'pqiv -i "$@"', desc = "Pqiv Image Viewer" },
]
text = [
	{ run = 'nvim "$@"', block = true, desc = "Neovim Text Editor"},
]

music = [
{ run = 'ffplay -nodisp -autoexit "$@"' },
]

video = [
{ run = 'ffplay "$@"' },
]

[open]

rules = [

{ name = "*.gif", use = "image" },

{ name = "*.jpg", use =  [ "image", "imageedit" ] },

{ name = "*.png", use =  [ "image", "imageedit" ] },

{ name = "*.conf", use = "text" },

{ name = "*.toml", use = "text" },

{ name = "*.txt", use = "text" },

{ name = "*.ini", use = "text" },

{ name = "*.jsonc", use = "text" },

{ name = "*.yml", use = "text" },

{ name = "*.json", use = "text" },

{ name = "*.lua", use = "text" },

{ name = "*.md", use = "text" },

{ name = "*.css", use = "text" },

{ name = "*.js", use = "text" },

{ name = "*.mp3", use = "music"},

{ name = "*.wav", use = "music"},

{ name = "*.ogg", use = "music"},

{ name = "*.mkv", use = "video"},

{ name = "*.mp4", use = "video"}

]
